<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Try Catch</title>
  <link rel="stylesheet" href="css/style.css">
  <script src="../externJsFile/try-and-catch-block.js" defer></script>
</head>

<body style="font-family: cursive">
  <h1>Try Catch</h1>
  <p>we use this more when we use asynchronus code basically in async functions code</p>
  <p>it is used for error handling</p>
  <p>whenwe write code and error comes whole execution will stop but with this we can solve this problem</p>
  <p>try and catch are made for error handling somehow. so that is the reason that when try block works execution ends
    but when it comes to catch even if the block(catch) itself is executed the programme will still execute after the
    block beacuse the try and catch has single motive to let the programme run even if it catches any error</p>
  <p>after try block it also works but after finally code nothing will work</p>
  <p style="font-size: larger; font-weight: 600;">PS: after all block this does work all of the above is some damn lies
  </p>
  <a class="link-button" href="59-Async-await.html">PreviousPage</a>
  <a class="link-button" href="61-optinalChaining.html">NextPage</a>
</body>

</html>